# Generated by Django 3.0.3 on 2020-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20141120_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='department',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='coach',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phoneNum',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='politicalBackground',
            field=models.CharField(choices=[('', ''), ('群众', '群众'), ('共青团员', '共青团员'), ('积极分子', '积极分子'), ('预备党员', '预备党员'), ('党员', '党员')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='studentClass',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='teamCategory',
            field=models.CharField(choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='teamName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='teamRole',
            field=models.CharField(choices=[('', ''), ('队长', '队长'), ('团支书', '团支书'), ('队员', '队员')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='work',
            field=models.CharField(default='', max_length=400),
        ),
    ]
